### ISSUE TITLE
Sheepl crashes when using subtask_list before assignment

### ISSUE THREAD

**Issue by lorentzenman** [SpiderLabs/sheepl#7]
There is a bug in the RDP module, that could actually be coming from the parent class of the CLI that cause Sheepl to crash. 

Path is create a new sheepl, use 'RemoteDesktop' module, but before starting a new assignment, call subtask_list and this crashes the program.

`¬> python3 sheepl.py --interactive                                                                                                                                

>: create bug
[%] Creating Sheepl called 'bug'
[?] How long would you like bug to take to complete tasks?
#> Enter the time (e.g. 45m or 6h) : 1m
[!] Setting total time to 1m
[?] How fast can bug type? <default is 40ms between key>
#> Enter the typing speed <40> : 
Typing speed is 40 milliseconds
[>] Creating the file : output/bug.au3
[^] Global Typing Speed set to : 40ms delay
[>] Looping set to : True

bug >: task RemoteDesktop
[>] You have selected : RemoteDesktop

----------------------------------
[!] RemoteDesktop Interaction.
Type help or ? to list commands.
----------------------------------
1: Start a new block using 'new'
2: Assign subtasks using 'subtask'
3: Complete the interaction using 'complete'

Documented commands (type help <topic>):
========================================
assigned  complete     discard  new               subtask
back      credentials  help     show_credentials

Undocumented commands:
======================
subtask_list

bug >: remotedesktop :> subtask_list
Traceback (most recent call last):
  File "sheepl.py", line 181, in <module>
    main()
  File "sheepl.py", line 136, in main
    con.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/mlorentzen/SpiderLabs/sheepl/utils/console.py", line 180, in do_task
    self.csh.generate_task(task)
  File "/Users/mlorentzen/SpiderLabs/sheepl/utils/base/base_sheepl_class.py", line 182, in generate_task
    return task_class_name(self, self.cl)
  File "/Users/mlorentzen/SpiderLabs/sheepl/tasks/network/RemoteDesktop.py", line 276, in __init__
    self.TaskConsole.cmdloop()               
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
TypeError: do_subtask_list() takes 1 positional argument but 2 were given
`
Fix needs to check whether a new assignment is called before calling 'subtask_list'

**Comment by lorentzenman** [comment]
Finally got round to fixing this one. It was to do with a pass statement in the function. Also learned a nice approach where the CMD module needs the second argument, that is how the module works. You might not always want the second argument. 

For example do_something(self, arg). If you don't pass the second arg it will crash. So you can set the CMD function like this do_something(self, arg=None). It will then run whatever is inside the function and works as expected.

So now calling subtask_list inside the RDP session, shows all the assigned tasks for that assignment.
