### ISSUE TITLE
KeePass Help

### ISSUE THREAD

**Issue by aleemladha** [SpiderLabs/sheepl#9]
Hi , 

Trying to create a simulation of opening keepass. am getting this error. 

k2 >: keepass :> database_location database_location C:\Users\Administrator\Documents\database.kdp
[!] <ERROR> You need to start a new KeePass Interaction.
[!] <ERROR> Start this with 'new' from the menu.
[!] <ERROR> You need to supply the command for typing
k2 >: keepass :> new
[!] Starting : 'KeePass_0'

[*] KeePass_0
k2 >: keepass :> database_location C:\Users\Administrator\Documents\database.kdp
[*] KeePass_0
k2 >: keepass :> subtask 
[!] SubTasks are not supported in the this module
[*] KeePass_0
k2 >: keepass :> database_loca
[*] KeePass_0
k2 >: keepass :> help

Documented commands (type help <topic>):
========================================
back  complete  database_location  discard  help  new  subtask

Undocumented commands:
======================
subtask_list

[*] KeePass_0
k2 >: keepass :> complete
Traceback (most recent call last):
  File "./sheepl.py", line 181, in <module>
    main()
  File "./sheepl.py", line 136, in main
    con.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/kali/Desktop/sheepl/utils/console.py", line 180, in do_task
    self.csh.generate_task(task)
  File "/home/kali/Desktop/sheepl/utils/base/base_sheepl_class.py", line 182, in generate_task
    return task_class_name(self, self.cl)
  File "/home/kali/Desktop/sheepl/tasks/credentials/KeePass.py", line 230, in __init__
    self.TaskConsole.cmdloop()            
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/kali/Desktop/sheepl/tasks/credentials/KeePass.py", line 180, in do_complete
    KeePass.create_autoIT_block(self.csh, 
  File "/home/kali/Desktop/sheepl/tasks/credentials/KeePass.py", line 270, in create_autoIT_block
    KeePassAutoITBlock(
  File "/home/kali/Desktop/sheepl/tasks/credentials/KeePass.py", line 412, in create
    self.text_typing_block() +
  File "/home/kali/Desktop/sheepl/tasks/credentials/KeePass.py", line 374, in text_typing_block
    for command in self.commands:
AttributeError: 'KeePassAutoITBlock' object has no attribute 'commands'

**Comment by lorentzenman** [comment]
Hey aleemladha, thanks for taking the time to report this. Sorry it took my a while to reply, work and stuff has slowed dev down on this the last few months.
It looks to me like that module is not fully implemented so I will look at this over the next few days and aim to get a fix out next week.

**Comment by lorentzenman** [comment]
This has now been fixed. The new KeePass option takes a database location and a masterpassword so this can be used for credential keylogging to get access to the database.
